@echo OFF
:: Run the cmake command
cmake -G "Visual Studio 15 Win64" ^
  -D CMAKE_PREFIX_PATH:PATH="C:\Program Files\HDF_Group\HDF5\1.11.2\cmake" ^
  -D CMAKE_BUILD_TYPE=Release ^
  -D CGNS_ENABLE_FORTRAN:BOOL=OFF ^
  -D CGNS_BUILD_SHARED:BOOL=OFF ^
  -D CMAKE_STATIC_LINKER_FLAGS:STRING="/NODEFAULTLIB:library" ^
  -D CMAKE_EXE_LINKER_FLAGS:STRING="/NODEFAULTLIB:library" ^
  -D CGNS_USE_SHARED:BOOL=OFF ^
  -D CGNS_ENABLE_LEGACY=ON ^
  -D CGNS_ENABLE_64BIT=BOOL=ON ^
  -D CGNS_BUILD_CGNSTOOLS:BOOL=OFF ^
  -D CGNS_ENABLE_TESTS:BOOL=ON ^
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON ^
  -D CGNS_ENABLE_HDF5:BOOL=ON ^
  -D CGNS_ENABLE_PARALLEL:BOOL=OFF ^
  -D HDF5_BUILD_SHARED_LIBS:BOOL=OFF ^
  -D HDF5_NEED_MPI:BOOL=OFF ^
  -D HDF5_NEED_ZLIB:BOOL=OFF ^
  -D HDF5_NEED_SZIP:BOOL=OFF ^
         ../CGNS
 cmake --build . 
