name: CGNS documentation daily build from previous day

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  check_changes_build:
    name: Check for updates to documentation or source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CGNS documentation repository (master branch)
        uses: actions/checkout@v4.1.7
        with:
          ref: master
          repository: ${{ github.repository }}
          path: repos/cgns_doc
